services:
  - type: web
    name: kutlink-backend
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/kutlink-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_USERNAME
        fromDatabase:
          name: kutlink-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: kutlink-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: kutlink-db
          property: connectionString

databases:
  - name: kutlink-db
    databaseName: kutlink
    user: postgres
    plan: free
